// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0my0k27JwdvR6nTc8wTNOtXGRYF1iDDA',
    appId: '1:59536673405:web:654738ad5071a074487f14',
    messagingSenderId: '59536673405',
    projectId: 'pawpalforpets',
    authDomain: 'pawpalforpets.firebaseapp.com',
    storageBucket: 'pawpalforpets.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdClf-9qzB21_T7CR5aGzqUWj5PV1uKeM',
    appId: '1:59536673405:android:d5d3daeccca868b0487f14',
    messagingSenderId: '59536673405',
    projectId: 'pawpalforpets',
    storageBucket: 'pawpalforpets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UiM0O-f6sscQlQMtDhf5S-eEhE9V84g',
    appId: '1:59536673405:ios:afa225e2dba77356487f14',
    messagingSenderId: '59536673405',
    projectId: 'pawpalforpets',
    storageBucket: 'pawpalforpets.firebasestorage.app',
    iosBundleId: 'com.example.pawpalforpets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_UiM0O-f6sscQlQMtDhf5S-eEhE9V84g',
    appId: '1:59536673405:ios:afa225e2dba77356487f14',
    messagingSenderId: '59536673405',
    projectId: 'pawpalforpets',
    storageBucket: 'pawpalforpets.firebasestorage.app',
    iosBundleId: 'com.example.pawpalforpets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0my0k27JwdvR6nTc8wTNOtXGRYF1iDDA',
    appId: '1:59536673405:web:4d649ac0ad78a334487f14',
    messagingSenderId: '59536673405',
    projectId: 'pawpalforpets',
    authDomain: 'pawpalforpets.firebaseapp.com',
    storageBucket: 'pawpalforpets.firebasestorage.app',
  );
}
